MESSAGE(STATUS "Configure Cross Compiler")

SET(CMAKE_SYSTEM_NAME Linux)
SET(CMAKE_SYSTEM_PROCESSOR x86_64)
SET(TARGET_OS linux)
SET(TARGET_ARCH x86_64)
SET(TARGET_HARDWARE generic)
ADD_DEFINITIONS(-DTARGET_PLATFORM=5)

# set ${CMAKE_C_FLAGS} and ${CMAKE_CXX_FLAGS}flag for cross-compiled process
SET(CROSS_COMPILATION_ARCHITECTURE x86)

SET(CMAKE_C_COMPILER       ${TOOLCHAIN_ROOTDIR}/gcc)
SET(CMAKE_CXX_COMPILER     ${TOOLCHAIN_ROOTDIR}/g++)
