MESSAGE(STATUS "Configure Cross Compiler")

SET(CMAKE_SYSTEM_NAME Linux)
SET(CMAKE_SYSTEM_PROCESSOR x86_64)
SET(TARGET_OS linux)
SET(TARGET_ARCH x86_64)
SET(TARGET_HARDWARE generic)
ADD_DEFINITIONS(-DTARGET_PLATFORM=5)

SET(CMAKE_C_COMPILER       /usr/bin/gcc)
SET(CMAKE_CXX_COMPILER     /usr/bin/g++)
